# Generated by Django 3.1.1 on 2021-01-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_puntajes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=25)),
                ('clave', models.ManyToManyField(to='inicio.Encuesta')),
            ],
            options={
                'order_with_respect_to': 'clave',
            },
        ),
    ]
